name: Packer builder of Hetzner snapshots for Worker Nodes

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/worker_builder.yaml'
      - worker-node/**
      - scripts/**
      - '!scripts/kube_tools_control_plane.sh'
  
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/worker_builder.yaml'
      - worker-node/**
      - scripts/**
      - '!scripts/kube_tools_control_plane.sh'

env:
  PACKER_VERSION: "1.8.6" # or: "latest"
  # Herzner token
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  # Worker Node COR user pub key
  COR_NODE_SSH_PUB_KEY: ${{ secrets.COR_NODE_SSH_PUB_KEY }}

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Run 'packer init' on worker-node
        id: init
        run: "packer init worker-node/image.pkr.hcl"

      - name: Run 'packer validate' on worker-node
        id: validate
        if: github.event_name == 'pull_request'
        run: "packer validate -var-file worker-node/variables.pkvars.hcl -var 'commit_hash=${{ github.sha }}' worker-node/image.pkr.hcl"

      - name: Run 'packer build' on worker-node
        id: build
        if: github.event_name == 'push'
        run: "packer build -var-file worker-node/variables.pkvars.hcl -var 'commit_hash=${{ github.sha }}' worker-node/image.pkr.hcl"